# Generated by Django 5.2.3 on 2026-03-12 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=3)),
                ('units', models.PositiveIntegerField(default=1)),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('donor', models.ForeignKey(limit_choices_to={'role': 'donor'}, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['hospital', 'bloodbank']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=3)),
                ('units', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role__in': ['hospital', 'bloodbank']}, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Inventories',
                'unique_together': {('owner', 'blood_group')},
            },
        ),
    ]
