# Generated by Django 5.2.3 on 2026-03-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_address_user_city_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(default='scheduled', max_length=20),
        ),
    ]
